version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: symfony_mysql_dev
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_DATABASE: loto1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app2
    depends_on:
      - db
    environment:
      APP_PATH: ${APP_PATH}
      WORKING_DIR: ${WORKING_DIR}
      PROJECT_NAME: ${PROJECT_NAME}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      APP_ENV: dev
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html

  phpmyadmin:
      depends_on:
          - db
      image: phpmyadmin
      restart: always
      ports:
          - 8082:80
      environment:
          PMA_HOST: db
